### ISSUE TITLE
Allow more than three columns

### ISSUE THREAD

**Issue by greeny** [fangyi-zhou/factorio-nuclear-power#1]
It would be nice if you could add columns in the same way as adding rows.

**Comment by fangyi-zhou** [comment]
I thought about that, but is there any particular layout you have in mind you wish to make? I'm new to these designs so I'm genuinely curious if there are any designs larger than 3x3 without refueling issues/

**Comment by fangyi-zhou** [comment]
By the way, take that as a yes, will add it over weekends

**Comment by greeny** [comment]
> I thought about that, but is there any particular layout you have in mind you wish to make? I'm new to these designs so I'm genuinely curious if there are any designs larger than 3x3 without refueling issues/

well for example with Bob's inserters you can have a diagonal inserter, which allows for design like
```
.RR.
RRRR
RRRR
.RR.
```
Which is not possible to calculate with your calculator at the moment (but don't take me wrong, it's great, just limited to vanilla setups).

**Comment by fangyi-zhou** [comment]
Oh I see, I didn't know about diagonal inserters mods, TIL

**Comment by fangyi-zhou** [comment]
Increased max columns to 6. 747c5a94344bd05b9797a0c32c102881d5245743
